version: "3.8"

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always

    acme-companion:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        environment:
            - DEFAULT_EMAIL=
        volumes_from:
            - nginx-proxy
        volumes:
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always

    nuxt-app:
        image: nuxt-app
        build: .
        restart: always
        expose:
            - "3000"
        environment:
            - VIRTUAL_HOST=
            - LETSENCRYPT_HOST=
    db:
        container_name: db
        image: postgres:alpine3.19
        restart: always
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    conf:
    vhost:
    html:
    certs:
    acme:
    postgres-data:
